/// <summary>
/// Save is update or insert
/// Load is Init
/// </summary>
public enum Tag
{
    // Save & Load : 1000
    SAVE_PLAYER_NORMAL_DATA_REQUEST, // Save Player Normal Data
    SAVE_PLAYER_NORMAL_DATA_RESPONSE,
    
    LOAD_PLAYER_NORMAL_DATA_REQUEST,
    LOAD_PLAYER_NORMAL_DATA_RESPONSE,
    
    SAVE_PLAYER_ABILITIES_REQUEST, // Save Player Abilities Statuses and Skills
    SAVE_PLAYER_ABILITIES_RESPONSE,
    
    LOAD_PLAYER_ABILITIES_REQUEST,
    LOAD_PLAYER_ABILITIES_RESPONSE,
    
    SAVE_INVENTORY_REQUEST, // Save Player Inventory Items and Equipments
    SAVE_INVENTORY_RESPONSE,
    
    LOAD_INVENTORY_REQUEST,
    LOAD_INVENTORY_RESPONSE,
    
    SAVE_ACHIEVEMENTS_REQUEST, // Save Player Quests and Achievements
    SAVE_ACHIEVEMENTS_RESPONSE,
    
    LOAD_ACHIEVEMENTS_REQUEST,
    LOAD_ACHIEVEMENTS_RESPONSE,
    
    SAVE_PLAYER_PARTY_REQUEST, // Save Player Company Pet and Employees
    SAVE_PLAYER_PARTY_RESPONSE,
    
    LOAD_PLAYER_PARTY_REQUEST,
    LOAD_PLAYER_PARTY_RESPONSE,

    SAVE_MAIL_REQUEST, // Save Player Mail
    SAVE_MAIL_RESPONSE,
    
    SAVE_FRIENDS_REQUEST, // Save Player Friends
    SAVE_FRIENDS_RESPONSE,
    
    LOAD_FRIENDS_REQUEST,
    LOAD_FRIENDS_RESPONSE,
    
    LOAD_RESOURCES_REQUEST,
    LOAD_RESOURCES_RESPONSE,
    
    SAVE_WALLET_REQUEST, // Save Virtual Currency
    SAVE_WALLET_RESPONSE,
    
    LOAD_WALLET_REQUEST,
    LOAD_WALLET_RESPONSE,
    
    SAVE_PREMIUM_INVENTORY_REQUEST, // Save Package Inventory
    SAVE_PREMIUM_INVENTORY_RESPONSE,
    
    LOAD_PREMIUM_INVENTORY_REQUEST,
    LOAD_PREMIUM_INVENTORY_RESPONSE,
    
    // Economy : 2000
    PURCHASE_CURRENCY_REQUEST, // Request Purchase Currency
    PURCHASE_CURRENCY_RESPONSE,
    
    PURCHASE_PACKAGE_REQUEST, // Request Purchase Package
    PURCHASE_PACKAGE_RESPONSE,
    
    PURCHASE_ITEM_REQUEST, // Request Purchase Item , Unit
    PURCHASE_ITEM_RESPONSE,
    
    REFUND_CURRENCY_REQUEST, // Request Refund Currency
    REFUND_CURRENCY_RESPONSE,
    
    REFUND_PACKAGE_REQUEST, // Request Refund Package
    REFUND_PACKAGE_RESPONSE,
    
    REFUND_ITEM_REQUEST, // Request Refund Item
    REFUND_ITEM_RESPONSE,
    
    USE_CURRENCY_REQUEST, // expense currency
    USE_CURRENCY_RESPONSE,
    
    USE_ITEM_REQUEST, // expense item
    USE_ITEM_RESPONSE,
    
    USE_PACKAGE_REQUEST, // expense package level
    USE_PACKAGE_RESPONSE,
    // 
    // Communication : 3000
    
    SEND_EMAIL_REQUEST, // to user
    SEND_EMAIL_RESPONSE,
    
    SEND_FEEDBACK_REQUEST, // to developer
    SEND_FEEDBACK_RESPONSE,
    
    SEND_MESSAGE_REQUEST,   // chat
    SEND_MESSAGE_RESPONSE,
    
    SEND_PARTICIPAION_TODAY_REWARD_REQUEST, // today reward
    SEND_PARTICIPAION_TODAY_REWARD_RESPONSE,
    
    SEND_PARTICIPAION_EVENT_REQUEST, // global event
    SEND_PARTICIPAION_EVENT_RESPONSE,

    // Battle Logic
    SEND_COMMAND_ORDER_QUEUE_REQUEST, // to server
    SEND_COMMAND_ORDER_QUEUE_RESPONSE,
    
    SAVE_BATTLE_ENVIRONMENT_REQUEST,
    SAVE_BATTLE_ENVIRONMENT_RESPONSE,
    
    LOAD_BATTLE_ENVIRONMENT_REQUEST,
    LOAD_BATTLE_ENVIRONMENT_RESPONSE,
    
    SEND_BATTLE_REWARD_REQUEST,
    SEND_BATTLE_REWARD_RESPONSE,
    
    PVP_MATCHING_REQUEST,
    PVP_MATCHING_RESPONSE,
    
    PVP_BATTLE_REWARD_REQUEST,
    PVP_BATTLE_REWARD_RESPONSE,
    //

}